### ISSUE TITLE
肥肠仰慕课程邮件都要用bot发的大佬

### ISSUE THREAD

**Issue by zeruniverse** [Armour/Gmail-Bot#1]

**Comment by Armour** [comment]
orz 噗这是顺便帮力耕弄的 据说是要用来给他们测model然后自动发结果回去 0 0

**Comment by zeruniverse** [comment]
肥肠仰慕cv还能用travis-ci的大佬（虽然好像没什么问题

**Comment by Armour** [comment]
诶嘿 最近转成用circle-ci了 之前有很多travis-ci的估计都没管就忘了hhh

**Comment by zeruniverse** [comment]
Circle-ci 有新功能？

**Comment by Armour** [comment]
有free plan 不用花钱 travis以后学生过了就要花钱了。。就很烦。。

**Comment by zeruniverse** [comment]
Private不要钱？这么屌
